packages/client/src/world/controller.ts, packages/client/test/chatui/chatui.test.ts
**Group**: Darren Hong, Andrew Mei
**Bug Description** (Issue #40): When finishing a conversation (chatting) with an NPC, the player cannot talk with the same NPC unless the nearby Mobs List changes.
**What Changed**: We added a line of code in `controller.ts` for the `setChatting` function, where the list of `lastChatCompanions` is reset every time a conversation is finished. The function, `mobRangeListener`, compares the nearby mobs with the mobs the player has recently chatted with and resets the `lastChatCompanions` list whenever the conversation ends. This ensures that the same NPCs can be re-added to the chat companion list, even if they were recently interacted with, as long as they remain in range.
**Why**: Previously, to chat with the same NPC, the player would have to go out of …
=> fix: rechatting with npcs

packages/client/jest.config.mjs, packages/client/package.json, packages/client/test/chatui/chatui.test.ts, pnpm-lock.yaml
The CI was failing on main due to jest not being set up to mock the DOM / canvas.
[fix(tests): move mocks into beforeEach](https://github.com/sloalchemist/potions/commit/6a0748dc56e89be288e7cc2f2688307bb14f657e)
- There was an issue "TypeError: Cannot read properties of undefined (reading 'Container')" when setting up the mocks outside of the beforeEach.
[chore(client): switch jest to jsdom environment](https://github.com/sloalchemist/potions/commit/11b6a0058e417d25d7b55e7c0b149e5ebe7375c5)
- Some tests require mocking the canvas, which requires test to run in the jsdom environment. This was set as the default for all tests in client
=> fix: CI failing on client tests

packages/client/src/scenes/loadWorldScene.ts
**Group:** Daniel Ching, Josh Queja
On the start screen, clicking cancel when the character name window appears displays the invalid name alert.
https://github.com/sloalchemist/potions/commit/8841c1482e11ba02abeedd5cb856facc675c9011
- If the window prompt is null, exit the function early and do not display alert
- UI change only, no unit test needed
=> Fix: don't display alert when cancel is pressed

packages/client/src/world/mob.ts, packages/client/test/world/mob.test.ts
Closes #44 
This PR resolves the bug where mobs with an already calculated path can pass through newly created walls. Our fix checks at every tick whether the next step in the mob's path is occupied by an unwalkable item in the world's grid. If it is, the mob recalculates its path to avoid the obstacle.
NOTE: branch name indicated issue 49 should actually by 44
`/client/src/world/mob.ts`
- `tick()`: We add additional checks and logic for regenerating the mob's path in the world. Utilizing the mob's path attribute and the `isWalkable()` method of the item at the next step, we determine if the mob is able to proceed or if it needs to recalculate its path.
`/client/test/world.mob.test.ts`
- Unit tests for the new logic in the `tick()` method.
- Test the mob's constructor to ensure that it …
=> Fix: Issue 44 - mobs already pathing into the fenced area do not respect player fences (Ryan Hu, Ryan Chan, Kyle Taschek)

packages/client/src/sprite/sprite_item.ts, packages/client/test/sprite/healthbar/itemHealthBar.test.ts, pnpm-lock.yaml
Group Members: Tyler Pham, Ethan Vos, Taran Singh
#Bug: Fence displays no health bar despite losing health
When the player uses the smash interaction on a fence or a wall, no health bar appears causing confusion to the player regarding the destructibility of the fence or wall.
#Changes
- Added optional instance variables for healthBar, health, and maxHealth in the SpriteItem class in packages/client/src/sprite/sprite_item.ts 
- Updated the constructor for SpriteItem to include initialization of the healthBar, health, and maxHealth for items that are of the 'fence' and 'wall' type
- Added new class method in SpriteItem, updateHealthBar(), to update the displayed health bar based on the percentage of health remaining if the item has a health bar
- Updated the destructor for SpriteItem to …
=> Bug fix fence no health

packages/client/static/global.json, packages/server/src/items/purchasable.ts, packages/server/src/items/uses/stand/retrieve.ts, packages/server/src/items/uses/usesConfig.ts, packages/server/test/items/itemRetrievePotionFromStand.test.ts
Fixes [#31](https://github.com/sloalchemist/potions/issues/31)
Before the fix, when a player added a potion to a potion stand, the only way to retrieve that potion was to purchase it. Players should not need to buy back their own potions. We believe there should be a way to pick up a potion from a stand. 
-  `packages/client/static/global.json`: Added retrieve_item interaction to potion-stand.
-  `packages/server/src/items/purchasable.ts`: Added retrieveItem method to Purchasable class to transfer item from stand to mob.
-  `packages/server/src/items/uses/stand/retrieve.ts`: Created stand/retrieve.ts to define retrieval.
-  `packages/server/src/items/uses/usesConfig.ts`: Added Retrieve action.
- `packages/server/test/items/itemRetrievePotionFromStand.test.ts`: Tested functionality -- mob …
=> Fix: Bug 31 Players cannot pick up their own potion after adding to a potion stand

packages/client/src/scenes/uxScene.ts, packages/client/src/sprite/sprite_mob.ts, packages/client/src/world/mob.ts, packages/client/src/worldMetadata.ts, packages/client/test/chatui/chatui.test.ts, packages/client/test/world/mob.test.ts, packages/common/src/mob.ts, packages/server/src/items/potionEffects.ts, packages/server/src/mobs/mob.ts, packages/server/src/services/clientCommunication/ablyService.ts, packages/server/src/services/clientCommunication/clientMarshalling.ts, packages/server/src/services/clientCommunication/pubsub.ts, packages/server/src/services/clientCommunication/stubbedPubSub.ts, packages/server/test/items/potionEffects.test.ts, pnpm-lock.yaml
- Changed the functionality of the blue potion from simply removing health. Now increases player speed. Also works with any mob who purchases and consumes a blue potion. Caps speed at 10 (which is REALLY fast), and is currently permanent until rebuild of game to refresh state.
- `packages/server/src/mobs/mob.ts` Added a 'changeSpeed' method.
- `packages/server/src/items/potionEffects.ts`  Added a call to 'changeSpeed' to replace the old 'changeHealth'. Adds 2 speed to the player, capping at 10.
- `packages/server/src/services/clientCommunication/pubsub.ts`  Added 'changeSpeed' signature.
- `packages/server/src/services/clientCommunication/stubbedPubSub.ts` Added 'changeSpeed' signature.
- `packages/server/src/services/clientCommunication/ablyService.ts` Added 'changeSpeed' method for …
=> Feat: Blue potions no longer decrease health, but rather increase player speed

packages/client/src/world/controller.ts, packages/client/test/items/uses/smashGate.test.ts
When approaching a smashable item that is walkable and has a layout_type of "opens" (i.e. a gate or a door), there is no button to smash that item.
This issue arose because any items that were walkable but not able to be stood on top of (i.e. a closed gate or door) were getting filtered out from having a smash interaction. 
1. Added logic for items who have a layout_type of "opens" to be checked if they were in proximity to the player's position
2. Now all nearby, openable items were added to the array of items that could be interacted with
Added one test case for gates and one for doors that checked if the respective object was interactable from a player location one tile away, and it checked if one of the interactions with this object was that it could be smashed.
=> Fix: resolved openable, smashable bug (Gabe Riedel, Calahan Lackovic)

packages/client/src/sprite/sprite_item.ts
**Group:** Daniel Ching, Josh Queja, Keith Lee
When starting the game, we noticed items had health bars. Logs and blueberries are items that should not show health bars. 
https://github.com/sloalchemist/potions/commit/1c9adc7729b80734e4a4ff4642f87c259901fcd4
- Removes adding the health bar graphic to every item unconditionally
- UI change only, no unit test needed
=> fix: don't display health bar for all items

packages/common/src/coord.ts, packages/common/src/pathFinder.ts, packages/common/test/pathFinder.test.ts
Whenever the user double-clicks to get to a point that is on the other side of an unwalkable area, they cut through the edges of the unwalkable area/tiles. This mainly occurs when near the top of the unwalkable areas.
We found that the issue arises because the pathing algorithm floor of the current point as the start (even if it is in between 2 tiles). The issue occurs when the second click happens as the current point is in between 2 tiles, so it considers the start as the floor, which makes it skip one of the points along its intended path.
- Added a ceiling method for coordinates
- Added a check to see if the floored start coordinate has an unwalkable area next to it (depending on the location of the target)
- Using that check, the starting coordinate is chosen as the ceiling or the …
=> Fix: Bug - User can walk over edges of water bodies

packages/client/src/sprite/sprite_mob.ts
Fix: Wall Can be Built From Partial Wall 
Fixed a bug where the "doingText" of the mob was not visible on yellow background. 
`C:\Users\halli\369\potions\packages\client\src\sprite\sprite_mob.ts` : 
- Changed color of text to black, increased font size from 10px to 12 px 
- added white border to doing text
=> fix: mob NPC text color

packages/server/test/items/itemDropping.test.js
Since our clear item interactions bug (https://github.com/sloalchemist/potions/issues/64) is a work in progress (clear_items branch), we've written a test for the functionality that was not originally covered. This test checks if a player successfully dropped an item.
=> test: testing functionality of picking up and dropping an item (Sri Bala, Melissa Chow)

packages/client/src/world/controller.ts, packages/client/test/items/uses/smashPartialWall.test.ts
Previously when the player would place a partial wall(non-walkable object) it would register twice:
- once as a nearby object
- once as an object the player is on top
We now are enforcing that the list of objects that interactions are based on is unique so it will only prompt one interaction.
=> Bug Fix: Only 1 interaction when the player is on top of a non-walkable object

packages/client/src/scenes/loadWorldScene.ts, packages/client/src/scenes/worldScene.ts, packages/client/src/services/serverToBroadcast.ts
Group: Andrew Estrada, Ethan Handelman
**Bug Description**
After the player's health is reduced to zero causing death, the game-over screen appears but there is no way to respawn in-game without refreshing the page through the browser.
**Changes Made**
Created function resetToLoadWorldScene() which waits three seconds before stopping all scenes that are currently active and restarting the LoadWorldScene. This effectively returns the client to the start of the game.
Added RESPAWN_DELAY constant to set delay for start game scene to be shown (in ms)
`packages/client/src/scenes/worldScene.ts`
Added call to resetToLoadWorldScene() in handling of player death
`packages/client/src/services/serverToBroadcast.ts`
Added init() function to reset lastAnimationKey to blank, ensuring proper rendering …
=> Return to start/load game screen after death

packages/client/src/sprite/sprite_item.ts, packages/client/test/sprite/healthbar/itemHealthBar.test.ts
Group: Darren Hong, Andrew Mei
**Bug Description** (Issue #104): When smashing the gate fence or the door, the health bar will not show. 
**What Changed**: We adjusted the if statement in `sprite_item.ts` and added `layout_type === 'open'`, representing both the gate and the door, allowing the health bar to be present when the player presses the smash command.
**Why**: This addition of the health bars allows the player to know the progress of getting rid of the door and gate. This also removes confusion on whether or not the gate and the door can be broken. It makes showing health bars consistent since fences also have this feature.
Before:
After:
=> fix: doors and gates have no healthbar

packages/client/src/sprite/sprite_item.ts, packages/client/src/world/item.ts, packages/client/src/world/world.ts, packages/client/src/worldDescription.ts, packages/client/static/global.json, packages/client/test/tsconfig.json, packages/client/test/world/mob.test.ts, packages/client/test/world/pathing.test.ts, pnpm-lock.yaml
Problem Statement:
Currently player cannot move through gate, even when it is open.
Solution Overview:
Added attribute to openable item type to check if item has been opened during pathing. Open gates shouldn't block pathing. 
Testing:
Created a new unit test and manually tested
=> Bug Fix Cannot Walk Through Open Gates

packages/common/src/pathFinder.ts, packages/common/test/pathFinder.test.ts
In general, when trying to move to an unwalkable tile, the user does not move anywhere. So, the fix to this would be to get to the closest walkable location/tile to the point that they originally clicked.
Another issue that stems from this is that when the user is already moving along a path and then clicks on an unwalkable tile, the user character just stops in place (no matter where it is, even if in between tiles; the character simply freezes and feels awkward on the user side. So, we want to eliminate this by allowing the user to walk as close as they can to the unwalkable tile.
- Implemented a new function called findNearestWalkableTile() that performs a breadth-first search from the unwalkable end coordinate by checking all 8 of its adjacent tiles, and finds the first walkable tile. …
=> Fix: Bug - Clicking on an unwalkable tile causes user to stop in the middle of their path

packages/server/src/community/community.ts, packages/server/test/items/giveItemToVillager.test.ts, packages/server/test/testSetup.ts
Fixed logic that prevented players and villagers from giving each other items despite having an alliance. Wrote a tests case and added logic to testSetup to support the test case.
=> fix: players now able to give items to villagers

packages/client/src/sprite/sprite_item.ts, packages/client/src/sprite/sprite_mob.ts
Changes
- Add drawing depth for sprite_items and sprite_mobs to the top
- Closes #172
=> fix(client): Increased the depth of health bars to the top

packages/server/test/template/itemTemplate.test.ts, packages/server/test/template/mobTemplate.test.ts
Linking issue #221  - Adding item and mob server test templates. This will prevent the need to create boiler plate in the future for server tests.
=> Feature: Create item and mob test templates

packages/client/src/sprite/sprite_item.ts, packages/client/src/sprite/sprite_mob.ts, packages/server/test/items/smashableItemHealthBar.test.ts
Health bars would not display over items that existed such as walls. (You couldn't see door health bars in the village when smashing them). Corrected the graphics so the health bar would show.
=> Fix: Fixed health bar not displaying over items

packages/server/cli/cheatHandler.ts, packages/server/cli/index.ts, packages/server/src/server.ts, packages/server/test/cli/cheatHandler.test.ts, packages/server/test/testSetup.ts
Closes #187 
**Summary**
This PR adds command line options to allow devs to test in the game environment through the same terminal they started the server in. 
The current commands implemented are:
- `spawn mob [type] x:[x-coord] y:[y-coord]`
- `spawn item [type] x:[x-coord] y:[y-coord]`
- `help: display command usage`
- `exit: quit CLI`
The work done is a starting point for the larger, more robust cheat framework we plan to develop in future PRs, which includes a standalone package for the cheat interface with an expanded list of commands and options for the future when servers are hosted in the cloud. 
**Changes**
`/server/src/server.ts`
- add cheat command listener
`/server/cli/cheatHandler.ts`
- async readline listener
- argument parsing and handling
- add help command to list usage …
=> [Feature] Cheat CLI for spawning mobs and items (Ryan Hu, Ryan Chan, Kyle Taschek)

packages/client/src/scenes/uxScene.ts, packages/client/src/sprite/sprite_mob.ts, packages/client/src/world/mob.ts, packages/client/src/worldMetadata.ts, packages/client/test/chatui/chatui.test.ts, packages/client/test/world/mob.test.ts, packages/common/src/mob.ts, packages/server/src/mobs/mob.ts, packages/server/src/mobs/mobFactory.ts, packages/server/src/mobs/traits/personality.ts, packages/server/src/services/authMarshalling.ts, packages/server/src/services/clientCommunication/ablyService.ts, packages/server/src/services/clientCommunication/clientMarshalling.ts, packages/server/src/services/clientCommunication/pubsub.ts, packages/server/src/services/clientCommunication/stubbedPubSub.ts, packages/server/test/mobs/mob.test.ts
Group: Darren Hong, Andrew Mei
**Bug Description** (Issue https://github.com/sloalchemist/potions/issues/209): Making sure the Player Profile can present the attack stats and personality stats, as well as making them mutable for any future features. 
**What Changed**: We changed `mob.ts` in the common folder to allow all MobIs to contain personalities. We added functions in `mob.ts` in the server folder to where the stats can be mutable. In `clientMarshalling`, we formatted the personality data so that the client is able to read it. In `uxScene`, we updated User Interface to contain new attacks and personality stats. The default values of the stats were already provided by the `global.json` in the server folder. We used `community_id` for the players affiliation and is unmutable.
Result:
=> Player profile

.github/workflows/client-deploy.yml
This pull request introduces a new GitHub Actions workflow to automate the build and deployment process for the client application. The main changes include setting up the workflow configuration and defining the necessary steps to build and deploy the client to GitHub Pages.
New GitHub Actions workflow for client build and deployment:
* [`.github/workflows/client-deploy.yml`](diffhunk://#diff-2a168ae6a3fe9a92c1a507f63ae7e5e6889cf01a4df2f8bc93f9ec4369f3e794R1-R60): Added a new workflow named "Build and Deploy Client" that triggers on pushes to the main branch and allows manual triggering. The workflow includes steps for checking out the repository, setting up Node.js, installing PNPM, installing dependencies, creating an environment file, building the client, copying static files, and …
=> Add Client Production Deployment on GitHub Pages

packages/client/src/scenes/loadWorldScene.ts, packages/client/src/scenes/worldScene.ts, packages/client/src/services/serverToBroadcast.ts, packages/server/src/mobs/mob.ts
**Group:  Ananya Thapar, Caroline Koddenberg, Adam Mikacich**
**Refactor description:**
Previously, when a player's health dropped to zero, the game would simply display "Game Over," requiring a refresh to restart. This PR introduces a respawn feature that allows players to continue without refreshing. Now, when a player dies, two buttons appear: Respawn and Menu. Clicking Respawn revives the player inside the portal. If the "destroyed mob" is of type player, their gold is reduced by half. If the mob is an NPC, their gold remains unchanged.
**What changed:**
`loadWorldScene.ts`
- Exported buttonStyle and nameButtonHoverStyle for use in the Respawn and Menu buttons.
`worldScene.ts`
- Added UI components for the new buttons.
- Stopped all gameplay-related scenes upon death.
- Restarted the …
=> 196 feature respawn after death

.github/workflows/client-deploy.yml
ACCESS_GITHUB_TOKEN is not the correct one for actions
=> fix: use GITHUB_TOKEN for client deploy

packages/client/src/services/playerToServer.ts
During merging of https://github.com/sloalchemist/potions/pull/271, two lines were accidently deleted that display the speech bubble.
**Changes**
https://github.com/sloalchemist/potions/commit/781980d1abd284b1a01e5de086a7c961e89b1833
- Correctly display the speech bubble
=> fix: display speech bubble on speak

packages/server/src/services/developerCheats.ts, packages/server/src/services/setup.ts, packages/server/src/services/supabaseStorage.ts
We simplified the upload/download data process by merging the WAL file into the db file, then only uploading the db file. This is not only simpler, but also fixes a rogue bug with the previous implementation.
In addition, the file being uploaded now includes the world ID, allowing for multiple worlds to be saved.
=> Simplify Upload/Download Data Process & Allow For Multiple Worlds to be Saved

packages/server/src/mobs/mob.ts
NPCs were cutting corners and walking over areas where they technically are not supposed to.
The reason was very similar to why the user was able to cut corners and walk over unwalkable areas, which was due to the fact that the start coordinate was getting floored and therefore a key point in the path gets missed. So, we removed the code for flooring the start position in the setting move target function for the mobs as it is already handled in the path finding algorithms in the common package.
Didn't write any tests for this as tests already exist for the path finding in the common package tests and this was a minor change to ensure the npc movement is like the user movement.
**Fixes** [#112](https://github.com/sloalchemist/potions/issues/112)
=> Changed NPC Movement Behavior so They No Longer Walk Over Water

.github/workflows/client-deploy.yml
The Supabase change just released did not change Node Version in the client build workflow causing the deploy to fail in Render. The required node version is 20 or higher, so I have updated to node 20 for them.
=> Upgrade Node Version for Supabase Change

packages/client/src/world/controller.ts, packages/client/test/items/uses/playerCarriedItems.test.ts
Group: Daniel Ching, Josh Queja, Keith Lee
When a player possesses an item and encounters a mob that already holds an item, the option to give the item to the mob should not appear. Functionally, nothing happens if the button is pressed.
https://github.com/sloalchemist/potions/commit/4d9c9ffddc882e8206f310730cab5b9c793abf58
- Check if mobs are carrying items before adding the 'give' interaction
- Created `playerCarriedItems.test.ts` to verify presence/absence of 'give' interaction
=> fix: prevent give item interaction if mob is carrying

README.md
This pull request includes a minor update to the `README.md` file. The change corrects the URL for the OtterWise coverage badge to point to the correct repository.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R3): Updated the OtterWise coverage badge URL to point to the correct repository.
=> fix: typo in coverage badge link

packages/client/src/sprite/sprite_mob.ts, packages/client/src/world/controller.ts, packages/client/src/world/mob.ts, packages/client/test/items/uses/playerPermissibleInteractions.test.ts, packages/client/test/items/uses/smashGate.test.ts
We've been working on implementing ownership (community and individual). In doing this, we found that the client and server weren't properly communicating item ownership (and mob community). 
Last week we synchronized ownership information for items between the client and server. Unfortunately, our method for communicating Mob Community was not optimal and we needed to address this issue a different way. Inconsistencies were still happening between client-side behavior and the authoritative server state.
This PR resolves the issue. 
- modified: `packages/client/src/world/controller.ts`: Access player through world.mobs within getPhysicalInteractions.
- modified: `packages/client/src/sprite/sprite_mob.ts`: Added community_id.
- modified: `packages/client/src/world/mob.ts`: Added …
=> Fix #369: Client / Server Mob Community Communication for Controller Interactions

packages/server/src/services/clientCommunication/ablyService.ts
After dying for the first time, player max health becomes the value of their attack.
Fix: Set player health to the correct value in `packages/server/src/services/clientCommunication/ablyService.ts` when sending player data after dying instead of setting it to the player's attack value.
Unit Tests: None
=> fix max health being attack value after death

packages/client/src/scenes/worldScene.ts
When opening the chat for players to type in, if they type the WASD keys, the player will move in the game world while at the same time typing those keys in the chat.
Fix: If `ChatOverlayScene` is active then return from `handlePlayerMovement` function.
Unit Tests: None
=> prevent player movement with WASD when chat is open

packages/client/src/scenes/uxScene.ts
Group: Darren Hong, Andrew Mei
Bug Fix for #364 
**Description**: The effects UI for the Handbook tab stayed when switching over to the Fight tab. We fixed this by setting the problematic containers to not be visible when switching to the Fight tab in `uxScene.ts`.
Before:
After:
=> fix: The effects UI is set to not visible when switching to fight tab

packages/client/src/sprite/sprite_mob.ts, packages/client/src/world/controller.ts, packages/client/test/items/uses/playerPermissibleInteractions.test.ts, packages/client/test/items/uses/smashGate.test.ts
Previously, the controller was using global variables to determine which interactions should be available to players on the client side.
This refactor makes it such that ownership identifiers are passed into getPhysicalInteractions(), making it simpler to implement individual ownership. Also this will make unit testing cleaner.
- modified `packages/client/src/world/controller.ts`: Refactor getPhysicalInteractions to recieve an ownerId to determine permissible interactions such that it is not relying on global variables.
- modified `packages/client/src/sprite/sprite_mob.ts`: Add id field to sprite_mob.
- modified `packages/client/test/items/uses/playerPermissibleInteractions.test.ts`: Remove globally defined mock variables.
- modified `packages/client/test/items/uses/smashGate.test.ts`: …
=> Refactor #394: Client-side Permissable Interactions

packages/client/package.json, packages/client/src/main.ts, packages/client/webpack.config.js, packages/server/package.json, packages/server/src/services/database.ts, pnpm-lock.yaml
Closes: #408 
**Summary**
This PR adds support for live reloading of source files in the server and client packages. When running `pnpm dev`, changes to the source files will be automatically picked up without needing to build and restart the local instances.
**Changes**
`packages/server/package.json`
- modified `dev` script to use nodemon
`packages/server/src/services/database.ts`
- added `SIGUSR2` handler to reload database on restart
`packages/client/package.json`
- installed `webpack-dev-server` for webpack live reloading
- installed `html-webpack-plugin` to render HTML template
`packages/client/src/main.ts`
- added handler function to accept hot module updates and trigger a reload
`packages/client/webpack.config.js`
- added support for hot module replacement
**Testing**
- Tested …
=> Live reloading for server and client dev scripts

README.md, tf.ps1, tf.sh
Added explicit instructions in a new readme section called TERRAFORM STATE SYNC PROBLEMS to address an issue a student had with terraform. Also, added better error handling for this case.
=> 392 adding explicit restart instructions for terraform

packages/client/src/world/controller.ts, packages/client/test/items/uses/playerBasketInteractions.test.ts, packages/json-generator/global.json, packages/server/data/global.json
Added permissions to baskets in respective global.json files to prevent non-affiliated species from having the button to add to baskets. I wrote unit tests, but here is UI/UX proof that the buttons correctly disappear now.
=> Fix: added permissions to baskets 

packages/common/src/serverBroadcast.ts, packages/json-generator/global.json, packages/server/src/items/carryable.ts, packages/server/src/items/item.ts, packages/server/src/mobs/mob.ts, packages/server/src/services/clientCommunication/ablyService.ts, packages/server/src/services/clientCommunication/pubsub.ts, packages/server/src/services/clientCommunication/stubbedPubSub.ts, packages/server/test/mobs/favorability.test.ts
Implements favorability changes depending on whether the mob is given their favorite item, and randomizes that mobs' favorite item.
There was no implementation for favorability changes depending on whether or not that mob is given their favorite item. This PR fixes that, and also implements a rule for making sure the mechanic cannot be abused.
Closes #435 
There weren't really many other alternatives considered, since the favorite item should be intrinsic to each mob. The implementation was relatively straightforward.
No breaking changes.
Will not impact any other developers. The change is relatively localized.
No developers need to be notified of the change.
Tested to make sure the favorability between the players' community and mobs' community changes depending on whether or not they …
=> 435 implement favorite item favorability

packages/client/src/sprite/sprite_item.ts, packages/client/src/world/controller.ts, packages/client/src/world/item.ts, packages/client/test/items/uses/playerBasketInteractions.test.ts, packages/common/src/item.ts, packages/server/src/community/house.ts, packages/server/src/generate/generateWorld.ts, packages/server/src/items/item.ts, packages/server/src/items/itemGenerator.ts, packages/server/src/items/purchasable.ts, packages/server/src/items/uses/create.ts, packages/server/src/mobs/mob.ts, packages/server/src/services/clientCommunication/clientMarshalling.ts, packages/server/test/actions/create.test.ts, packages/server/test/items/stand/itemCommunityOwnershipPotionStandInteractions.test.ts, packages/server/test/potions/favorabilityBasedPotionPurchase.test.ts, packages/server/test/walls/startWall.test.ts
Every instance of ownedBy was changed to ownedByCommunity so that we may introduce ownedByCharacter for individual ownership of items. 
We previously implemented community based ownership. We also need to create the possibility of individual ownership of items. In order to do this, we can use ownedBy logic already in use, but we need two instances of each ownedBy attribute: one for community and one for an individual. 
Closes issue #472 
We could've overwritten community based ownership to implement individual, but there are features that now rely on community based ownership and we didn't want to introduce problems. 
The only team that might be impacted by this is the favorability team. But none of their previously written code is affected. 
We will notify them of the change. 
Since this …
=> 472 refactor ownedby ownedbycommunity

packages/client/src/scenes/worldScene.ts
- Simple bug fix in worldScene.ts to fix incorrect passing of width and height parameters
- closes issue #528 
- this solved the problem of the night overlay not fully covering all of water world
- no alternatives were considered as the error was quite small
- this bug fix was a simple change of width/height mix up and does not require notification
- bug is in the UI so I went through water world and went around the perimeter during night time and saw the whole area covered as expected
- repeated these steps for fire-world and test-world to double check
After
Before
=> Bug Fix: Night Overlay Display

packages/client/src/scenes/portalMenuScene.ts
When clicking "Enter Portal" no longer shows worlds that are down, checks health of server, and does not show current world.
1. Doesn't show current world which you wouldn't need to tp to as you are on
2. If user were to tp to world that is down, there would be no way to change their world id in the production database back to a world that could host them. Essentially, that character is lost until the world comes back up.
3. Closes #554 
Not checking world health status. 
I have hardcoded the world-names to their IDs on the uptime service. Do no believe this is a problem as no new worlds will be added and our worlds on that service will not be edited or deleted.
No breaking
If developers are trying to change world locally, they would be able to if they ran the servers themselves, but now, …
=> fix: Made portal button not appear for worlds down or for current world

packages/common/src/pathFinder.ts, packages/common/test/pathFinder.test.ts
Updated the findNearestWalkableTile function to return targets closest to the player when there are multiple options for the closest tile to the original target.
Before this changes, when you clicked on an unwalkable tile, you would pathfind to the closest tile to your target. However, when there were multiple closest tiles, you would always go to the rightmost one (due to how the breadth first search was implemented). Instead, when there are multiple options, the player should pathfind to the tile closest to them. 
Simply sorting the 8 neighbors by proximity to the player ensures that closest options are considered first. Sorting can be slow, but since the input is small, this change is not felt by the player. One option considered was looking at everything on the queue, then returning …
=> Improve Pathfinding When Target is Unwalkable

packages/client/src/scenes/uxScene.ts, packages/client/src/sprite/sprite_mob.ts, packages/client/src/world/mob.ts, packages/client/src/worldMetadata.ts, packages/client/test/items/uses/playerBasketInteractions.test.ts, packages/client/test/items/uses/playerCarriedItems.test.ts, packages/client/test/items/uses/playerCharacterPermissibleInteractions.test.ts, packages/client/test/items/uses/playerCommunityPermissibleInteractions.test.ts, packages/client/test/scenes/uxSceneChat.test.ts, packages/client/test/scenes/uxSceneFight.test.ts, packages/client/test/world/mob.test.ts, packages/common/src/mob.ts, packages/server/src/community/community.ts, packages/server/src/mobs/mob.ts, packages/server/src/services/clientCommunication/ablyService.ts, packages/server/src/services/clientCommunication/clientMarshalling.ts, packages/server/src/services/clientCommunication/pubsub.ts, packages/server/src/services/clientCommunication/stubbedPubSub.ts
Added a new feature where the user (alchemist) can see what favorability they have with each community (blobs, silverclaw, fighters, and future communities)
Closes #568 
We implemented this where the player can press the **_F key_** and the numbers will appear. Originally, we believed that it should be in the Player tab, but we recognized that it will make more cluttered than it should be. We have chosen this approach as we believe that it should be easily found, in case the player wants to keep track of favorability when doing some type of action. Like what is done with the potions handbook, this reduces the amount of tabs in the UI. 
A new attribute, favorabilities, was added into the `mob.ts` in the `common` folder for this implementation.
This change added a new parameter for mobs so …
=> feat: Added Community Favorabilites to Player Info UI

packages/json-generator/global.json, packages/server/global.json, world_assets/global/client/global.json, world_assets/global/server/global.json, world_assets/water-world/server/world_specific.json
The visual of the shipwreck is now visible in Oozon. the next steps will be to make the ship transparent when the character walks behind it.
World Enhancement
World Enhancement
The changes were tested through temporary local asset files instead of pulling from GitHub Pages. The world_assets folder files have been updated and therefore will reflect the changes in GitHub Pages. All appropriate files were edited to add the new item, therefore no impact should occur.
Replaced GitHub Pages assets with local ones temporarily to test the new item placement.
=> Adding in shipwreck to water world

README.md
Added README documentation to help avoid ECONNREFUSED error in server when building.
closes issue #566 
When the 'pnpm run create world-name' command is ran in server there appears an AggregateError 'ECONNREFUSED'.
This will allow devs the peace of mind knowing this error is not causing major issues during build time with a simple fix.
No testing required - running auth server fixes it.
=> documentation: ECONNREFUSED error

packages/client/src/config.ts, packages/client/src/scenes/leaderboardScene.ts, packages/client/src/scenes/loadWorldScene.ts, packages/client/src/scenes/miniLeaderboardScene.ts
Added button feature to show and hide leaderboard (See Screenshots)
The leaderboard was taking up a large portion of the screen. This change allows users to better move around the map with their cursor and is a quality of life change.
You could move the leaderboard into a tab, however this would defeat the purpose of having it show on the main screen. Ultimately chose implementing buttons as it is a quick solution that accomplishes the goal. 
Does not impact other dev teams or devs.
Tested the screenshots through manual testing as it UI. Please see screenshots for two different states of button.
=> 552 fix leaderboad display

packages/auth-server/src/authController.ts, packages/client/src/services/ablySetup.ts, packages/client/src/services/playerToServer.ts
Created another ably channel for chat messages to display chat bubble when client receives messages.
Players will now be able to communicate via text chat.
Before this change, the message was not being sent anywhere to publish to other clients. It was just showing up on a singular client's side.
Testing not required.
To have confidence that it worked with other clients, we opened up an incognito tab to simulate multiple clients subscribing to the ably channel.
=> publish chat messages to clients

packages/auth-server/package.json
Auth server was refactored to have tests, but the package.json wasn't updated to have start point to the new src folder.
Auth server doesn't start.
Made it point to the right place.
Auth server starts
It works!
=> fix: auth server start points to wrong place

packages/server/src/services/clientCommunication/ablyService.ts
World persistence blows up right now if the player dies at an inopportune time.
Patches the issues above to not crash. I'm logging an error instead and I abort from the persistence method.
This persistence & presence code is not great. I'm sure there is a better solution but trying to get the server to stay up.
Server stops crashing.
I retriggered the error and it no longer crashes. Seems to work much better now.
=> fix: log error rather than crash when mob not found on persistence

packages/client/src/scenes/worldScene.ts, world_assets/water-world/server/world_specific.json
Transparency to the shipwreck when character walks behind it.
Character was not visible behind the shipwreck
Alternative consideration was to disable walking behind the shipwreck.
No dev impact.
Manual testing on personal env.
=> Transparency of ship when character walks behind it

packages/client/static/global.json, packages/json-generator/global.json, packages/json-generator/src/schema.ts, packages/json-generator/test/expectedClient.json, packages/json-generator/test/expectedServer.json, packages/server/global.json, world_assets/global.json
These changes restores the functionality that was overwritten and fixes the individual-based ownership interactions that were not applied to the client side through JSON configuration files. 
Changing these files, the client side can now:
* carry items that are owned by player
* have individual permissions instead of community
* more flexible and dynamic configurations with `community`, `character`, and `other`
These changes are required to make the server and client permissions consistent with each other, and allowing players to have more access and actions in the game. 
Alternative approaches like creating new permission types were considered, but the current method was chosen to avoid unnecessary complexity while being flexible and simple. By using optional()  for the fields, the …
=> Fix #636: Individual based ownership interactions not applied to client side via global.jsons

packages/server/src/items/uses/create.ts, packages/server/test/actions/create.test.ts
Updated create.ts to properly create a potion stand from a log. 
This prevents a null type potion from being created on smashing the potion stand. 
Modifying the creation of a market stand in create.ts seemed to be more general than modifying the behavior of smashable.ts to only check if the type is a log. 
Minimal impact, only added an additional check to prevent a default item count to be 1. 
However, a new function to add potions to this empty market should be added in another pr. 
Passed all automatic testing.
Add test, if potion still created when a log created market is smashed.
=> Fix: breaking log based potion stands doesn't create a null potion

packages/server/src/items/item.ts, packages/server/src/items/uses/pickup.ts
Update item.ts to add a message to the pubsub when a gold item is deleted for marshaling. 
This prevents phantom gold that appears on the client side from accumulating for the most part. They still appear it seems to be from another bug, but this fixes the server side of things.
Considered implementing client side approach to deleting gold on npc collision and player pickup, but put on hold for sake of time.
Minimal impact to the code base as it only adds one line to broadcast the destruction of gold items to the pub sub whenever gold is picked up and another to check for the action. 
Only manually testing to view if gold was marshaled. The pubsub functions are already tested and since this change only requires an additional call to broadcast a destroy for gold items we felt it was …
=> fix: add broadcast to delete gold item

packages/client/src/scenes/worldScene.ts
Adding a short cut keyboard interactions on top of the WASD including and not limited to:
1. Picking up item with keyboard on <e/E> 
2. Dropping item with keyboard on <e/E> (if item is on hands)
In the current state of the game, it becomes difficult to toggle actions using on game buttons, so adding a feature to play the game using the keyboard adds smooth and intuitive user interaction. 
Initial thought was to have a separate **Keyboard** buttons for each interaction, but from UX perspective it would be harder for the user to remember all possible hotkeys, so we used **Apple's Home Button** idea to toggle the same button for different tasks depending on the state of the process.
1. This might require a HotKey Documentation update
2. During the client side testing, it will be easier and …
=> Keybinds for common interactions. Issue #578

packages/server/src/items/uses/enterPortal.ts, packages/server/test/actions/enterPortal.test.ts
Instead of populating worlds in the constructor of enter portal class, I populate them when interact is called
#649 
All interaction items are called and their constructor is called during "pnpm run start <world>" causing an error to appear as getWorlds() is called which requires auth-server connection. This error is confusing and can be avoided.
I was going to make the interact ufnction async and await the populateWorlds() function but that causes issues down the line as you must return a boolean, not a Promise.
doesn't break anything, just removes error during create script
Manually tested to see if portal would still show worlds
Removed tests that dealth with old constructor. Tests still with interactions as interactions are not changed.
previous, error on build
current
=> fix: lazily load worlds from auth server at run time to prevent error in "pnpm run create <world>"

packages/server/src/services/clientCommunication/ablyService.ts
When a player leaves the game (or loses focus), the server updates the player data in the DB and then removes the player from the world. The server awaits the update in order to ensure the order is correct.
Previously these two actions had no guaranteed order, resulting in a race case where the player upload would crash the server since it was trying to upload information from a player that was not in the world. This is a more permanent solution to #597
This approach was chosen give the simplicity of it. This approach seemed obvious, so no others were considered.
No impact on developers. Servers should stop crashing when the game loses focus.
I manually lost focus 25 times, and the race case error did not hit. This, plus the logic of it, makes me think it has been solved for.
=> Fix Player Not Found Bug When Updating Player State 

packages/client/world_assets/global.json, packages/json-generator/global.json, packages/json-generator/test/expectedClient.json, packages/json-generator/test/expectedServer.json, packages/server/world_assets/global.json
Removes villager-world exclusive items from spawning in water world
Closes issue #596
n/a
- Confirmed this was a bug with the product team
- Had to fix hardcoded json test files to ensure json generator worked correctly - confirmed this with team that wrote the test
Walked around all locations with seaweed in water-world and confirmed these times were not spawning
no more sunflowers or sun-drops
=> bug: fixed incorrect items spawning in water world

packages/server/src/items/uses/marketstand/createMarket.ts, packages/server/test/items/marketstand/createMarket.test.ts
Upon placing a Marketstand in front of a gate, this messes with the NPC pathing behavior and completely breaks any gathering behavior by NPCs.
This change is required as players could place Marketstands in front of gates and completely destroy any NPC gathering that would occur. 
This solution presents the simplest option to solving this problem. There is no reason to abstract this issue to other items as other placed items are walkable (meaning they can be walked through).
This change is self isolated and was appropriately tested in a unit test.
This functionality is tested within createMartket.test.ts with a mock test automatically.
=> 676 bug placing potion stands in front of gate ruins npc pathing

packages/server/src/mobs/mob.ts, packages/server/test/potions/potionEffects/blackPotion.test.ts
When spawning a monster, ID is hardcoded so we can only create one monster at a time.  Randomize names/ID of monster spawned by black potion to be able to create multiple. 
Closes #621 
We still want to differentiate monsters from regular blobs, so the name should include 'Monster'. We also want to differentiate from other monsters. It's easiest to just spawn the monster with an randomized ID/name which will allow you to insert multiple monsters into mobs.
Not much impact in terms of notification/shouldn't affect anyone else that much.
Changed automated tests to grab monster by name similarity ('Monster %') and made sure tests still pass. Added test for multiple monsters.
=> Fix Black Potion - Can Spawn Multiple Monsters

packages/client/world_assets/global.json, packages/json-generator/global.json, packages/json-generator/test/expectedClient.json, packages/json-generator/test/expectedServer.json, packages/server/world_assets/global.json
PR #678 reverted a bug fix in PR #671. This PR just adds those changes back in. I copied their file changes to multiple global.json files... as far as I know, it just removes villager-world exclusive items from spawning in water world. Refer to their PR for more info.
=> fixed overridden bug fix from PR #671

packages/client/src/scenes/uxScene.ts
Group: Daniel Ching, Josh Queja, Keith Lee
The keybinds manual screen should be toggleable with the "k" key. Currently there is no way to dismiss it besides manually clicking another tab.
https://github.com/sloalchemist/potions/commit/af47eeafe3efffa9e551d3a235af544e88dc6969
- Dismiss the keybinds manual screen when "k" is pressed
=> fix: toggleable keybinds manual screen

packages/client/src/scenes/worldScene.ts
The "GAME OVER" text appearing when the player dies can be obscured by mob health bars. This change ensures the "GAME OVER" text is always on top.
Closes #687 
None
Aesthetic effect only
Manual testing confirms health bar is no longer obscured.
=> Fix healthbars obscuring "GAME OVER" text 

tf.ps1, tf.sh
Added new custom error messages for various errors related to tf.ps1 and tf.sh scripts 
This is important so that developers unfamiliar with the terraform workflow can get back to work faster instead of having to worry about debugging. 
"Closes #653 " 
No alternatives were considered as this method has worked for previously handled errors. 
Extra messages were added so there was no change to the design or tradeoffs of the current method of error handling. 
This change does not break anything and does not require documentation because it essentially is documentation.
This change should make it easier for developers to get to the point of being able to work on the project faster.
Nobody needs to be notified.
Changes were not tested beyond checking to see that the custom error message pops …
=> 653 certain terraform errors arent being caught by custom error handling

packages/client/src/world/controller.ts, packages/client/test/scenes/uxSceneChat.test.ts
Filters the blobs out of chat options.
You should not be able to talk to the blobs, they exist solely for combat in the current implementation.
This will remove blobs from chat options and have no external impacts
- Unit Testing
- Manual Testing
=> [BugFix] Filter Blobs from Chat Options

packages/client/src/sprite/sprite_item.ts, pnpm-lock.yaml
Changed the condition for the side walls of a house to change. Intitially would change when smashed one time if there was no wall above the one being smashed. It worked fine when smashing a wall with no wall below as long as there was a wall above. I made it so that it works both ways.
When smashing the side wall without another wall above it, the sprite changed from being a side wall into the default top wall, which was buggy.
Just changed the conditions.
does not break anything, just minor visual bug fix.
manual tested, no automated testing needed.
=> fixed conditions to change sprite when smashing a side wall

packages/client/src/services/serverToBroadcast.ts, packages/client/src/world/controller.ts, packages/client/src/world/item.ts, packages/client/test/items/uses/playerCarriedItems.test.ts
Previously, the user was given the option to stash an item even if they had a full inventory. Now, the stash button doesn't populate when inventory is full.
Closes [Issue #580](https://github.com/sloalchemist/potions/issues/580).
This issue was originally raised because of a bug in which the user could not drop an item after attempting to stash it with a full inventory. However, while addressing that issue I realized (with the help of @spruhaN) that it made more sense to just not provide the option to stash when inventory is full. That is what this PR accomplishes.
This change should not have any significant effect on other developers.
Tested manually.
=> Stash Button Shouldn't Populate with Full Inventory

packages/server/src/services/dbOperations.ts, packages/server/src/services/supabaseStorage.ts, packages/server/test/supabaseStorage/supabaseStorage.test.ts, pnpm-lock.yaml
If object storage upload fails, the server used to crash. Now, it logs the error without crashing. I also separated out the db operations into their own file for better organization and testability.
Previously if there was a transient error that caused object storage to fail, the entire server would crash and need to be manually restarted. Fixes #665 
I considered different levels at which to catch the error but eventually decided that uploadLocalData() in `supabaseStorage.ts` was the right choice. 
This does not impact developers, except those who have had to manually reboot the server after an object storage upload error, they will be happy.
I added several tests in `supabaseStorage.test.ts` to make sure that when errors are thrown from the supabase object storage sdk, they are caught …
=> Fix: Prevent server world from crashing if the upload to object storage fails

packages/client/world_assets/global.json, packages/json-generator/global.json, packages/json-generator/test/expectedClient.json, packages/json-generator/test/expectedServer.json, packages/server/world_assets/global.json
Removed all instances of 'destroy stand' in JSON files
The existing 'destroy stand' button performs no functionality and the desired functionality can be achieved with the existing 'smash potion stand button'
Could have removed 'smash potion stand' and added the functionality 'destroy stand' but requires extra work when an existing button with the desired functionality already exists. 
No breaking changes made
Went into the world and made sure breaking potion stands both with and without potions was possible. 
example of destroy stand and smash potion stand buttons
=> Fix: removed redundant stand smash/destroy for potion stands

packages/client/src/services/serverToBroadcast.ts
We added a check to see if the LeaderBoardScene (the expanded version) is active before calling the rerenderLeaderBoard function. 
This change cleans up console warnings with error stack traces that occur when the expanded LeaderBoardScene has not been created by Phaser at the start of the game (because the miniLeaderBoardScene is default). It is most likely that the code was initially structured under the assumption that the expanded leaderboard would always be there and did not change to handle the new edge case when the option of a collapsed leaderboard was added.  As a small added benefit, it makes the code more efficient by not attempting to rerender a scene that is not active. 
Closes #726
We had initially thought to initialize the titleText within the constructor but this is not …
=> fix: the leaderboard will only call rerender if it is active

packages/server/src/services/gameWorld/serverWorld.ts
Fix serverworld.ts tick function that had duplicate calls for tick functions for conversationTracker and FantasyDate. Also updated DataLogger calls, since it calls the wrong function causing some metrics to not be updated. 
Closes #740 
No trade-offs made 
No impact on codebase
No testing needed functions are already tested
=> fix: remove duplicate calls causing excessive updates

packages/server/src/items/potionEffects.ts, packages/server/test/potions/potionEffects/toxicPotion.test.ts
When drinking a potion whose brew color is close to black (i.e, a potion made from tar), a closeToBlack function is called which immediately kills the player. The potion from which the player drank is now deleted from the world
Closes [#738 ](url)
One decision that was considered was to just leave the potion in the world as the world is created anew when a player dies. However, this approach does not lend favorably to future plans in which we might want to save the world state to how it was before the player died, so that a player might pick up their items from where they previously died. In this scenario, the player could theoretically still use and drink the potion and have it exist forever since it does not despawn. Thus the decision to remove the potion immediately upon drinking was …
=> Delete Potion From World After Suicide

packages/client/src/components/button.ts, packages/client/src/components/tabButton.ts, packages/client/src/scenes/loadWorldScene.ts, packages/client/src/scenes/uxScene.ts, packages/client/src/scenes/worldScene.ts
Adding an option to toggle both music and sound effects in the game.
Both toggle buttons are in the `Player` tab of the console, taking up minimal space. When toggled off, the buttons are highlighted red, indicating that the user has switched those values to off. They can turn it back on by pressing the button once more.
Closes #699 
The main considerations in play included where the toggles should be added in the game interface as well as what the users should see when they're toggled off or on. We ultimately decided to add both toggles as small buttons on the `Player` tab, as it made the most sense for player/system-wide controls.
This provides players better customizability for their gameplay. By granting the ability to independently toggle off either sound effects or music, it …
=> 699 sfx music toggle

packages/client/src/components/button.ts
Centers buttons across all of the frame pages
Some final polishing, the off-centered buttons just lacked polishing
Changing the width and height instead of the spacing. Though current buttons are able to display all text appropriately so just made the page less crammed by changing the spacing.
This change does not break anything nor require documentation.
Ran against the potion build until altered spacing till it seemed appropriate.
Before:
After:
=> Enhancement: Centered Buttons

packages/server/src/grafana/dataLogger.ts
Added world names to metrics to separate metrics between servers. 
It separates the metric between worlds, allowing metrics to be useful in that each server's metrics can be differentiated now. 
Closes #691 
Initially we used the worldID from an another file export, but this caused test to fail from the dependency, so we just used the world name in the arguments to differentiate the servers. We used the world name, since it follows our current sharding scheme. This relies on each server running a unique world to separate the metrics. If worlds are ran on multiple servers, this may cause the metrics to be mixed again. 
No impact on codebase
Manually tested the name of the metric job to check it included the world name.
=> Separate world metrics from each other

packages/client/src/services/serverToBroadcast.ts
There was a client console warning that came up frequently that did not specify the location. It has to do with the handleDoing attempting to assign a 'doing' value to a mob that does not exist.
Closes #734 
This is simple fix that adds the location of the error and makes the overall error message smaller, so there is not really any alternative ways to do so.
This change does not affect other developers beyond being able to identify client console logs easier.
Ran the game to confirm the error was being properly handled
=> 734 fix: repeated nondescriptive client console warning "Cannot set properties of undefined"

packages/client/src/services/serverToBroadcast.ts
Added a condition on handleDoing to prevent errors on client. Also added a missing break statement in switch for processing server broadcast. 
The errors from handleDoing was blocking the ably broadcast from processing the entirety of the message causing missing delete actions for mobs and items. This caused the client to have a build up of phantom mobs that lagged the client side. 
The handleDoing code only needed a condition to check before setting an action for an undefined value. This was the simplest way to prevent the error from occur and by extension blocking. 
No impact on codebase.
Manually tested if errors appeared on client console.
=> Fix Phantom Mobs

packages/client/src/world/controller.ts, packages/client/test/items/uses/nonOwnerCommunityMemberPermissibleInteractions.test.ts, packages/client/test/items/uses/playerBasketInteractions.test.ts, packages/client/test/items/uses/playerCommunityPermissibleInteractions.test.ts, packages/client/world_assets/global.json, packages/json-generator/global.json, packages/server/world_assets/global.json
This PR updates the controller logic to correctly allow community members (who are not the owner) to see interactions that are available to other non-owners. It also updates affected client-side test cases by passing the mob ID to getPhysicalInteractions() and adds a test case to validate this behavior.
Previously, community members who were not the owner of an item (e.g., a potion stand) could not see interactions that were available to "other" players, even if permissions.other was true. This led to incorrect behavior, such as a community member being unable to purchase a potion from another community member’s stand.
Closes #763
The issue was caused by isOwnedByCharacter and isOwnedByCommunity both being true for the item's creator within `getPhysicalInteractions()` in `controller.ts`, …
=> Fix #763: Non-owner community ownership interactions

packages/client/world_assets/global.json, packages/json-generator/global.json, packages/server/world_assets/global.json
This PR updates market stand interactions to include character-based permissions. Previously, interactions like adding an item, purchasing, and adjusting prices were primarily community-based. This change ensures that characters (owners) can interact with their own market stands, while restricting non-owners appropriately.
Market stand interactions lacked explicit character-based permissions, allowing anyone within the community to perform restricted interactions like collecting gold.
Closes #764
- This approach was chosen to maintain consistency with how similar items work (e.g. potion stands).
- The update ensures that characters (owners) can always interact with their own market stand ("character": true).
- Community-based permissions remain configurable by altering …
=> Fix #764: Apply individual based ownership to market stand interactions

packages/client/world_assets/global.json, packages/json-generator/global.json, packages/server/world_assets/global.json
This PR updates potion stands and market stands to be walkable, allowing mobs and players to pass through them. This prevents players from creating impassable barriers that would block movement.
Potion and market stands were previously non-walkable. While this was not a problem in the past, both items will soon only be smashable by those who owned them. This change ensures that players and mobs can freely navigate around placed stands without being blocked.
Closes #773
Alternative solutions were considered, such as making stands decay over time and eventually disappearing. However, making stands walkable quickly fixes the problem while also making it less ambiguous as to which stand you are currently interacting with when surrounded by multiple stands as making it walkable now requires …
=> Fix #773: Make potion and market stands walkable

tf.ps1, tf.sh
Added new custom error messages for various errors related to tf.ps1 and tf.sh scripts 
This is important so that developers unfamiliar with the terraform workflow can get back to work faster instead of having to worry about debugging. 
"Closes #714" 
No alternatives were considered as this method has worked for previously handled errors. 
Extra messages were added so there was no change to the design or tradeoffs of the current method of error handling. 
This change does not break anything and does not require documentation because it essentially is documentation.
This change should make it easier for developers to get to the point of being able to work on the project faster.
Nobody needs to be notified.
Changes were not tested beyond checking to see that the custom error message pops up …
=> 714 more terraform custom error handling

packages/client/src/scenes/worldScene.ts, packages/client/world_assets/global.json, packages/server/world_assets/global.json
The original changes in #746 broke some animations and menu screen and as a result had to be rolled back. This pr adds the loading bar back in with several optimizations including lazy loading of audio so the initial game load is MUCH faster. Probably 5x.
#722 
same as #746 
same as #746
same as #746
same as #746
=> Add back world loading
