packages/client/src/world/controller.ts

**Summary**
This PR refactors and modularizes the interaction logic within the game world, making it more flexible and easier to test. The primary goal of this refactor was to ensure that different parts of the game logic are isolated for easier unit testing.
**Changes**
We have introduced isolated functions to handle different aspects of interaction processing:
- getCarriedItemInteractions: retrieves interactions available when the player is carrying an item.
- getPhysicalInteractions: handles interactions for physical items that are present in the world
- getClosestPhysical: finds the closest physical object to the player
- getInteractablePhysicals: combines logic to find items the player can interact with based on their position
collisionListener now calls the relevant helper …

Refactor: collisionListener abstractions for unit testing

---

packages/server/src/items/smashable.ts
packages/server/test/items/potionStandItemDrop.test.ts
packages/server/test/testSetup.ts

Bug 28
Potion Stand not dropping items when smashed. 
Fix:
Added functionality for potion stand to drop items when smashed.
Testing:
Created a test to check if the items would properly drop.
@AkashPraveen @ivannghi @ddharton

Bug 28 potion stand dropping

---

packages/client/static/global.json
packages/server/data/global.json
packages/server/src/items/item.ts
packages/server/src/items/on_ticks/spawnItem.ts
packages/server/test/items/itemSpawning.test.ts
packages/server/test/testSetup.ts

Created new func in item.ts
Edited itemSpawning.ts to account for new local max
Edited config files so spawn_item actions had new parameters (global_max, local_max, radius)
Created new test file

Fix item spawning

---

packages/server/test/creatingServerTests.md

Created `packages/server/test/creatingServerTests.md` to document everything a developer needs to know about creating a test in the server package. 
NOTE: Our documentation is based on the test refactoring mentioned in issue 151.
Linked Issue: #137

Documentation for Server Tests

---

packages/client/src/world/controller.ts
packages/client/test/items/uses/playerInteract.test.ts

Changes:
- closes #183 
- added test case under client/src/test/items/uses/playerInteract.test.ts
- modified controller.ts logic to return multiple distinct non-walkable objects next to player

Bug: Multiple Player Interactions Fixed

---

README.md
setup.ps1
setup.sh

Improves the quality of life for developers by simplifying and speeding up the process of setting up and running the game environment. The scripts are designed to automate repetitive tasks such as building the project, creating test worlds, and starting the necessary servers and clients, reducing the manual effort required.
The inclusion of command-line argument parsing allows developers to selectively run specific parts of the setup process, offering flexibility and easy modification, providing a way for integrating new steps to the setup process. This setup is useful for improving testing capabilities and enabling faster iteration cycles.

feat: Add build+run scripts

---

.github/workflows/ci.yml
Dockerfile

**Group:** Daniel Ching, Josh Queja, Keith Lee
To eventually support the deployment of the potions server on remote machines, we've added support for the **server** package to run in its own Docker container. Developers have the option to either run the server locally or inside the Docker container.
https://github.com/sloalchemist/potions/commit/13b0252bd89ec79c976bf4af1a6e0ac1d7a81bf4
- Created Dockerfile to configure and build the server package in the container
- Updated Continuous Integration Checks to verify Docker builds successfully
The Wiki page to setting up and running Docker can be found [here](https://github.com/sloalchemist/potions/wiki/Docker-Guide).

feat: Support Docker for server package

---

packages/auth-server/src/characterData.ts
packages/server/src/services/authMarshalling.ts
packages/server/src/services/clientCommunication/ablyService.ts

data correctly connects to supabase through auth-server from server

fix: 404 issue

---

packages/server/src/items/container.ts
packages/server/test/items/basketCapacity.test.ts
packages/server/test/testSetup.ts

Fixed #14 
Added a proper check to the container.ts file to limit capacity to its stated value
Had a ton of issues with merge conflicts for no good reason so I just force reset it to main and re added the changes since they were super small, unfortunately also lost all the history from that but it just wasn't working and I am the only one really affected by it so.

fixed: container capacity

---

.terraform-prod/main.tf
README.md
package.json
packages/server/src/services/setup.ts
packages/server/src/services/supabaseStorage.ts
pnpm-lock.yaml
terraform/main.tf
terraform/variables.tf

- Updated the node dependencies to a newer version where File is supported.
-  Removed the need for developers to manually create a bucket on Supabase. Instead code automatically generates it
- Added previously added environment variables to terraform

Update Node Dependency + Make Supabase Process with Terrafom

---

packages/client/static/global.json
packages/server/data/global.json

added tree and log back to global.json (in both server/ and client/). will develop more comprehensive solution soon.

Quick Fix for Global.json

---

packages/server/cli/cheatHandler.ts
packages/server/src/items/itemGenerator.ts
packages/server/src/mobs/mobFactory.ts
packages/server/test/cli/cheatHandler.test.ts

Improve the error messages to suggest that the issue is likely due to versioning and they should probably delete their current world in supabase

390 improve Unknown Item/Mob Error Messages

---

packages/server/data/global.json

fixes: #498
Fixes formatting to global json too

fix: readd portal interaction in global.json

---

packages/client/src/scenes/worldScene.ts

The player’s movement behavior has been fixed so that when any of the movement keys ('W', 'A', 'S', 'D') are pressed, the game will check for obstacles in the chosen direction. If there’s an obstruction, it will not move and the players position will be stagnant.
Given the nature of a blocked path, the player would around around the object. Not the intended behavior given the movement keys.
If the path is blocked, the player's movement will remain stagnant, and the `getItemAt` function from `client/src/world/world.ts` is used to determine if there is something in the way, checking for obstacles or blocked areas. The built-in `isWalkable` function from `client/src/world/item.ts` helps ensure that the player can only move through walkable spaces.
Changes the movement for players to be more …

Bug: Inconsistent Movement 

---

.github/workflows/ci.yml

Adds the merge group to the CI conditions, and once it is merged will enabled "Require Merge Queue" in the Branch protection Ruleset.
Currently, when contributors wish to merge their changes, they must ensure their changes are up-to-date with main.
Meaning whenever main changes (like someone merging their changes in), they must update their branch and
wait for CI to run again. If someone else merges in that time, then you must re-do the whole process over again (see #516)
This feature by Github (see [Github Merge Queue Announcement](https://github.blog/news-insights/product-news/github-merge-queue-is-generally-available/)) was designed specifically for this scenario and other large projects implement similar functionality to prevent traffic jams. 
This should help make developer's lives a …

feat: merge queue

---

packages/client/src/scenes/worldScene.ts

Changes movement to be more in sync with the server and fixes a small issue with holding down keys while moving. 
Closes #539 
Changes not able to be tested I believe.

Wasd movement out of sync

---

.gitignore
packages/json-generator/src/generator.ts
packages/server/global.json
packages/server/src/generate/buildWorld.ts
packages/server/src/services/setup.ts
world_assets/global/client/global.json
world_assets/global/server/global.json

Changes paths in `setup.ts` and `buildWorld.ts` to potions.gg URL instead of world_assets.
Closes [559](https://github.com/sloalchemist/potions/issues/559)
Client already imports via URL, so this changes server files to import via URL as well.
Fixes an existing issue. Should not affect others.
Used Render preview, tested manually on dev and prod.

559 setup.ts references files from outside of server package

---

packages/server/src/generate/buildWorld.ts
packages/server/src/services/setup.ts

This PR refactors the server to fetch the global.json configuration dynamically from a from https://potions.gg/world_assets/global/server/global.json rather than a static import in setup.ts and buildWorld.ts.
Previously, we used a statically imported global.json file. However, this requires manual updates and isn't scalable so we want to instead dynamically load the necessary data, allowing the system to automatically stay up-to-date with the latest version from the server.
An alternative approach would have been to continue using the static import and manually update it with every configuration change. However, dynamically fetching the configuration at runtime ensures that the server always uses the latest data, avoiding the need for manual updates. The trade-off of this approach is …

583 dynamic global data loading

---

.github/workflows/client-deploy.yml

fix: world assets deploy github action

---

packages/client/static/global.json
packages/client/world_assets/global.json
packages/json-generator/global.json
packages/json-generator/test/expectedClient.json
packages/json-generator/test/expectedServer.json
packages/server/world_assets/global.json

Similarly to the volcano the shipwreck now spawns gold, as the volcano spawns fireballs.
Closes #632
Due to the limited gold appearance, this is a source of truth location to find instant gold (at the location of the shipwreck).
No dev impact.
Manual testing on personal env.

Shipwreck spawns gold

---

packages/client/src/world/controller.ts

Generalized decision making for non-walkable interactions
Previously, this was set to specific items, this generalizes them. Previously, if a wall and fence were within a tile of the character It would not show.
This design might be slow because it creates a distance calculation for each object and then reverts them. 
This should not break anything else.
Manual Testing

707 fixing decision making for non walkables

---

packages/client/src/scenes/uxScene.ts

After picking up various items, it was difficult to remember the order in which they were acquired. Organizing the inventory alphabetically provides a more user-friendly experience.
Organizing inventory space to enhance visibility and make it easier for users to see available items.
Sorting was the only operation needed.
No testing needed, UX change

Enhancement: Changed Inventory to display in alphabetical order

---

packages/client/src/scenes/uxScene.ts

Aligned Eye Color, Belly Color, and Fur Color to match other formatting in player tab and changed the font size to match other attributes in the player tab.
Closes issue 719.
Leaving as is but the alignment/aesthetics of it were off.
No.
Manually tested.
Before:
After:

polished player tab

---

packages/client/src/scenes/uxScene.ts
pnpm-lock.yaml

Restored dynamic inventory counter that was previously removed
Closes #742 
Change is minimal and is meant to improve user experience
Did manual testing, checked for functionality and edge cases

Restored dynamic counter to inventory

---

packages/server/world_assets/water-world/world_specific.json

Previously waterworld spawned in a message in the bottle in an invalid location, changed it to a walkable coordinate.
Breaks if not.
Changes location
Ran and confirmed new location

Fix: Bottle placement in waterworld

---

packages/client/world_assets/global.json
packages/json-generator/global.json
packages/server/world_assets/global.json
packages/server/world_assets/test-world/world_specific.json
pnpm-lock.yaml

* Tar and lightning removed from village world, 
* Sands of time added
Closes https://github.com/sloalchemist/potions/issues/745
Editing items in the world to match the product vision
No impact 
Manually tested, played 5min in each world

Bug Fix: Village world edits

---

packages/server/src/util/logger.ts

Current Logger Was still very busy, now defaulted to the warn level. Still able to change levels with the commands

Changed default logger level

---

.gitignore

fix: Add server logs to gitignore
